In [ ]:
import numpy as np
img1 = np.random.randint(0, 256, (5, 5)) 
img2 = np.random.randint(0, 256, (5, 5)) 
print("Image 1 (5x5):\n", img1) 
print("Image 2 (5x5):\n", img2)

#  Vertical Stacking
v_stack = np.vstack((img1, img2))
print("\nVertically Stacked Image:\n", v_stack)

In [12]:

h_stack = np.hstack((img1, img2))
print("\nHorizontally Stacked Image:\n", h_stack)


Horizontally Stacked Image:
 [[206 103 127 143 153 102  82 158  30  23]
 [ 15  88 156 127  33 227  61 117 185 121]
 [224 102   8 121 162 173   9 145  43 234]
 [160  37  92 144 220 238 132 219 192 196]
 [ 78  31  62  13  12 180  30 129  23 137]]


In [14]:

# Split vertically stacked image into 2 parts (simulating segmentation)
v_split = np.split(v_stack, 2)
print("\nVertical Split (2 parts):")
for i, part in enumerate(v_split, 1):
    print(f"Part {i}:\n", part)

h_split = np.split(h_stack, 2, axis=1)
print("\nHorizontal Split (2 parts):")
for i, part in enumerate(h_split, 1):
    print(f"Part {i}:\n", part)


Vertical Split (2 parts):
Part 1:
 [[206 103 127 143 153]
 [ 15  88 156 127  33]
 [224 102   8 121 162]
 [160  37  92 144 220]
 [ 78  31  62  13  12]]
Part 2:
 [[102  82 158  30  23]
 [227  61 117 185 121]
 [173   9 145  43 234]
 [238 132 219 192 196]
 [180  30 129  23 137]]

Horizontal Split (2 parts):
Part 1:
 [[206 103 127 143 153]
 [ 15  88 156 127  33]
 [224 102   8 121 162]
 [160  37  92 144 220]
 [ 78  31  62  13  12]]
Part 2:
 [[102  82 158  30  23]
 [227  61 117 185 121]
 [173   9 145  43 234]
 [238 132 219 192 196]
 [180  30 129  23 137]]
