In [1]:
import numpy as np

# 1. Create a 3D array (6 students, 4 terms, 3 subjects)
grades = np.random.randint(50, 101, (6, 4, 3))  # random grades between 50–100
print("1. Grades Array Shape:", grades.shape)
print("Grades Array:\n", grades)


# 2. Vertical stacking (combine grades of 2 students)
student1 = grades[0, :, :]   # shape (4, 3)
student2 = grades[1, :, :]   # shape (4, 3)

v_stacked = np.vstack((student1, student2))  # shape (8, 3)
print("\n2. Vertically Stacked Grades of Student 1 & 2 (8x3):\n", v_stacked)


# 3. Transpose so that terms are first axis, students are last
# Original shape: (students=6, terms=4, subjects=3)
# Transposed shape: (terms=4, subjects=3, students=6)
transposed = np.transpose(grades, (1, 2, 0))
print("\n3. Transposed Grades Shape:", transposed.shape)
print("Transposed Array (terms, subjects, students):\n", transposed)


# 4. Split to get each subject separately
# Shape (6, 4, 3) → split along last axis into 3 subjects
subjects_split = np.split(grades, 3, axis=2)

print("\n4. Grades Split by Subject:")
for i, subject in enumerate(["Math", "Science", "English"], 1):
    subject_data = subjects_split[i-1].squeeze()  # remove extra dimension
    print(f"{subject} Grades (shape {subject_data.shape}):\n", subject_data)


# 5. Swap axes → swap terms (axis=1) and subjects (axis=2)
swapped = np.swapaxes(grades, 1, 2)  # shape (6, 3, 4)
print("\n5. Swapped Axes Shape:", swapped.shape)
print("Swapped Array (students, subjects, terms):\n", swapped)


# 6. Extract grades for 3rd student in Science across all terms
# Student index = 2, Science index = 1
student3_science = grades[2, :, 1]  # shape (4,)
print("\n6. Grades of 3rd Student in Science (all terms):", student3_science)


1. Grades Array Shape: (6, 4, 3)
Grades Array:
 [[[94 89 80]
  [82 61 51]
  [86 79 78]
  [53 72 53]]

 [[57 72 51]
  [87 81 60]
  [95 66 60]
  [54 89 73]]

 [[58 83 57]
  [80 84 54]
  [99 73 63]
  [55 55 69]]

 [[92 94 85]
  [84 85 68]
  [61 69 73]
  [84 54 95]]

 [[73 86 96]
  [83 98 81]
  [87 73 95]
  [78 54 55]]

 [[96 90 52]
  [70 67 70]
  [72 86 83]
  [95 92 91]]]

2. Vertically Stacked Grades of Student 1 & 2 (8x3):
 [[94 89 80]
 [82 61 51]
 [86 79 78]
 [53 72 53]
 [57 72 51]
 [87 81 60]
 [95 66 60]
 [54 89 73]]

3. Transposed Grades Shape: (4, 3, 6)
Transposed Array (terms, subjects, students):
 [[[94 57 58 92 73 96]
  [89 72 83 94 86 90]
  [80 51 57 85 96 52]]

 [[82 87 80 84 83 70]
  [61 81 84 85 98 67]
  [51 60 54 68 81 70]]

 [[86 95 99 61 87 72]
  [79 66 73 69 73 86]
  [78 60 63 73 95 83]]

 [[53 54 55 84 78 95]
  [72 89 55 54 54 92]
  [53 73 69 95 55 91]]]

4. Grades Split by Subject:
Math Grades (shape (6, 4)):
 [[94 82 86 53]
 [57 87 95 54]
 [58 80 99 55]
 [92 84 61 84]
