In [2]:
import numpy as np
# Step 2: Define the System of Linear Equations
A = np.array([[2, 3],
              [5, 7]])   # Coefficient matrix
b = np.array([8, 19])    # Constants vector

# Step 3: Solve Linear Equations
X = np.linalg.solve(A, b)

print("Solution (x, y):", X)




Solution (x, y): [1. 2.]


In [4]:
# Step 4: Matrix Operations

# Define another matrix B for multiplication
B = np.array([[1, 2],
              [3, 4]])

# Matrix Multiplication using np.dot()
result_dot = np.dot(A, B)
print("Matrix Multiplication using np.dot():\n", result_dot)

# Matrix Multiplication using np.matmul()
result_matmul = np.matmul(A, B)
print("Matrix Multiplication using np.matmul():\n", result_matmul)

# Inverse of Matrix A
A_inv = np.linalg.inv(A)
print("Inverse of Matrix A:\n", A_inv)

# Determinant of Matrix A
A_det = np.linalg.det(A)
print("Determinant of Matrix A:", A_det)

Matrix Multiplication using np.dot():
 [[11 16]
 [26 38]]
Matrix Multiplication using np.matmul():
 [[11 16]
 [26 38]]
Inverse of Matrix A:
 [[-7.  3.]
 [ 5. -2.]]
Determinant of Matrix A: -0.9999999999999987


In [5]:
# Define a matrix A (3x3 example)


print("Matrix A:\n", A)

# Step 5: Eigenvalues and Eigenvectors
eigenvalues, eigenvectors = np.linalg.eig(A)

print("\nEigenvalues:\n", eigenvalues)
print("\nEigenvectors (columns correspond to eigenvalues):\n", eigenvectors)

# Verification: A @ v = λ * v
for i in range(len(eigenvalues)):
    left = A @ eigenvectors[:, i]
    right = eigenvalues[i] * eigenvectors[:, i]
    print(f"\nCheck for eigenvalue {eigenvalues[i]:.4f}:")
    print("A @ v =", left)
    print("λ * v =", right)


Matrix A:
 [[2 3]
 [5 7]]

Eigenvalues:
 [-0.10977223  9.10977223]

Eigenvectors (columns correspond to eigenvalues):
 [[-0.81797819 -0.38876264]
 [ 0.57524923 -0.92133794]]

Check for eigenvalue -0.1098:
A @ v = [ 0.08979129 -0.06314639]
λ * v = [ 0.08979129 -0.06314639]

Check for eigenvalue 9.1098:
A @ v = [-3.54153912 -8.39317882]
λ * v = [-3.54153912 -8.39317882]
