In [1]:
import numpy as np

# 1. Create 3D NumPy array (5 cities, 7 days, 3 parameters)
weather_data = np.random.randint(0, 100, (5, 7, 3))  
# Parameters → Temperature, Humidity, Rainfall

print("1. Weather Data Shape:", weather_data.shape)
print("Weather Data:\n", weather_data)


# 2. Horizontal stacking (combine 2 cities' data side by side)
# We'll combine city 0 and city 1 data: each (7,3)
city1 = weather_data[0]  # shape (7, 3)
city2 = weather_data[1]  # shape (7, 3)

city_hstack = np.hstack((city1, city2))  # shape (7, 6)
print("\n2. Horizontally Stacked Data (City1 + City2):\n", city_hstack)

# If we want all 5 cities stacked side-by-side → shape (7, 15)
all_cities_hstack = np.hstack([weather_data[i] for i in range(5)])
print("\nHorizontally Stacked All Cities Shape:", all_cities_hstack.shape)  # (7, 15)


# 3. Transpose to swap cities & days → (7, 5, 3)
transposed = np.transpose(weather_data, (1, 0, 2))
print("\n3. Transposed Shape (7 days, 5 cities, 3 params):", transposed.shape)
print("Transposed Array:\n", transposed)


# 4. Split array along first axis (cities)
cities_split = np.array_split(weather_data, 5, axis=0)
print("\n4. Split into individual city data:")
for i, city in enumerate(cities_split, 1):
    print(f"City {i} Data Shape: {city.shape}\n", city)


# 5. Swap axes (swap cities and days → axes 0 and 1)
swapped = np.swapaxes(weather_data, 0, 1)  # shape (7, 5, 3)
print("\n5. Swapped Axes Shape (days, cities, params):", swapped.shape)
print("Swapped Array:\n", swapped)


# 6. Slice temperature data for Day 4 across all cities
# Day index = 3, Temperature index = 0
day4_temp = weather_data[:, 3, 0]  # shape (5,) → all cities' temperatures on day 4
print("\n6. Temperatures on Day 4 across all cities:", day4_temp)


1. Weather Data Shape: (5, 7, 3)
Weather Data:
 [[[72 74 10]
  [96 58 95]
  [45 10  8]
  [50 21 72]
  [68 51 72]
  [ 4 33 31]
  [58 75  9]]

 [[ 8 85 71]
  [28 84 54]
  [33 41 70]
  [87 32  4]
  [ 0 93 68]
  [50 93 79]
  [56 30 46]]

 [[ 8 40 67]
  [ 2 46 46]
  [14 21  7]
  [ 4 25 83]
  [56 39 53]
  [34 50 17]
  [85  3 60]]

 [[16 22 62]
  [59 20  1]
  [68 66  1]
  [92 68 31]
  [ 0  6 51]
  [91 52 37]
  [97 21 74]]

 [[58 90  8]
  [24 49 50]
  [44 96 83]
  [73 84 60]
  [84 31 16]
  [29 11 44]
  [69  5 89]]]

2. Horizontally Stacked Data (City1 + City2):
 [[72 74 10  8 85 71]
 [96 58 95 28 84 54]
 [45 10  8 33 41 70]
 [50 21 72 87 32  4]
 [68 51 72  0 93 68]
 [ 4 33 31 50 93 79]
 [58 75  9 56 30 46]]

Horizontally Stacked All Cities Shape: (7, 15)

3. Transposed Shape (7 days, 5 cities, 3 params): (7, 5, 3)
Transposed Array:
 [[[72 74 10]
  [ 8 85 71]
  [ 8 40 67]
  [16 22 62]
  [58 90  8]]

 [[96 58 95]
  [28 84 54]
  [ 2 46 46]
  [59 20  1]
  [24 49 50]]

 [[45 10  8]
  [33 41 70]
  [