In [1]:
import numpy as np

arr_1d = np.random.randint(1, 101, size=12)
print("1D array:\n", arr_1d)

arr_2d = arr_1d.reshape(4, 3)
print("\n2D array (4x3 matrix):\n", arr_2d)

second_row = arr_2d[1, :]
print("\nSecond row:\n", second_row)

first_column = arr_2d[:, 0]
print("\nFirst column:\n", first_column)


last_two_last_row = arr_2d[-1, -2:]
print("\nLast two elements from last row:\n", last_two_last_row)


print("\nArray shape:", arr_2d.shape)
print("Array size:", arr_2d.size)
print("Array data type:", arr_2d.dtype)


1D array:
 [36 16 29 40 27 23 86 45 29  9 33 30]

2D array (4x3 matrix):
 [[36 16 29]
 [40 27 23]
 [86 45 29]
 [ 9 33 30]]

Second row:
 [40 27 23]

First column:
 [36 40 86  9]

Last two elements from last row:
 [33 30]

Array shape: (4, 3)
Array size: 12
Array data type: int32
