In [1]:
import numpy as np

# Step 1: Create a 3D array
# Shape: (2, 3, 4) -> 2 time points, 3 regions, 4 temperature readings
data = np.random.randint(0, 100, (2, 3, 4))
print("Original 3D Array (2 time points, 3 regions, 4 temperature readings):\n", data)

# Step 2: Transpose the 3D array (swap the axes)
# Here, we reorder axes: (time=0, region=1, readings=2) -> (region=1, time=0, readings=2)
transposed_data = np.transpose(data, (1, 0, 2))
print("\nTransposed 3D Array (3 regions, 2 time points, 4 temperature readings):\n", transposed_data)

# Step 3: Swap axes (swap axis 0 and axis 1)
# Equivalent to transpose of only 2 axes
swapped_data = np.swapaxes(data, 0, 1)
print("\nSwapped Axes (3 regions, 2 time points, 4 temperature readings):\n", swapped_data)

# Step 4: Slice the 3D array (extract data for the first time point)
first_time_point_data = data[0, :, :]  # Pick time=0 → shape (3,4)
print("\nData for First Time Point (3 regions, 4 temperature readings):\n", first_time_point_data)


Original 3D Array (2 time points, 3 regions, 4 temperature readings):
 [[[34 98  7 80]
  [32 28 59 57]
  [ 9  7 66 50]]

 [[12  3 31 18]
  [51 32 55  9]
  [83 61 73 94]]]

Transposed 3D Array (3 regions, 2 time points, 4 temperature readings):
 [[[34 98  7 80]
  [12  3 31 18]]

 [[32 28 59 57]
  [51 32 55  9]]

 [[ 9  7 66 50]
  [83 61 73 94]]]

Swapped Axes (3 regions, 2 time points, 4 temperature readings):
 [[[34 98  7 80]
  [12  3 31 18]]

 [[32 28 59 57]
  [51 32 55  9]]

 [[ 9  7 66 50]
  [83 61 73 94]]]

Data for First Time Point (3 regions, 4 temperature readings):
 [[34 98  7 80]
 [32 28 59 57]
 [ 9  7 66 50]]
