In [1]:
import numpy as np

# Step 1: Create coefficient matrix A (3x3) and constant vector b (3x1)
A = np.random.randint(1, 10, (3, 3))  # Random 3x3 matrix with values 1–9
b = np.random.randint(1, 10, (3, 1))  # Random 3x1 column vector with values 1–9

print("Coefficient Matrix A:\n", A)
print("Constant Vector b:\n", b)

# Step 2: Solve the system A * x = b
x = np.linalg.solve(A, b)

print("Solution Vector x:\n", x)

# Step 3: Verify solution → A * x should equal b
b_check = np.dot(A, x)   # or use np.matmul(A, x)
print("Verification A * x:\n", b_check)
print("Does A*x equal b?\n", np.allclose(b, b_check))


Coefficient Matrix A:
 [[5 7 7]
 [2 3 1]
 [3 7 4]]
Constant Vector b:
 [[4]
 [1]
 [3]]
Solution Vector x:
 [[-0.04]
 [ 0.24]
 [ 0.36]]
Verification A * x:
 [[4.]
 [1.]
 [3.]]
Does A*x equal b?
 True
