In [5]:
import numpy as np

arr1 = np.random.randint(1, 101, 15)
print("Array:", arr1)

# Boolean masking: select values > 50
greater_than_50 = arr1[arr1 > 50]
print("Values > 50:", greater_than_50)

arr2 = np.arange(2, 41, 2)  # 20 even numbers (2 to 40)
print("Array:", arr2)

# Fancy indexing: select every third element
every_third = arr2[::3]
print("Every third element:", every_third)

arr3 = np.arange(1, 17).reshape(4, 4)
print("Array:\n", arr3)

# Boolean masking: elements > 10
greater_than_10 = arr3[arr3 > 10]
print("Elements > 10:", greater_than_10)

arr4 = np.random.randint(0, 10, 10)
print("Original Array:", arr4)

arr4[arr4 < 5] = 0
print("After replacement:", arr4)

arr5 = np.arange(1, 37).reshape(6, 6)
print("Array:\n", arr5)

selected_rows = arr5[[0, 2, 4], :]  # 0-based indexing
print("Rows 1, 3, 5:\n", selected_rows)

arr6 = np.random.randint(1, 101, 10)
print("Array:", arr6)

labels = np.where(arr6 > 50, "High", "Low")
print("Labels:", labels)

arr7 = np.random.randint(10, 51, (3, 3))
print("Array:\n", arr7)

max_index = np.unravel_index(np.argmax(arr7), arr7.shape)
print("Index of maximum value:", max_index)


arr8 = np.random.randint(0, 30, 12)
print("Array:", arr8)

conditions = [arr8 < 10, (arr8 >= 10) & (arr8 <= 20), arr8 > 20]
choices = ["Small", "Medium", "Large"]

# Specify dtype=object to allow string output
size_labels = np.select(conditions, choices, default="Unknown")
print("Size Labels:", size_labels)


arr9 = np.random.randint(-10, 10, 15)
print("Array:", arr9)

has_negative = np.any(arr9 < 0)
print("Contains negative values?", has_negative)

arr10 = np.random.randint(0, 101, 10)
print("Original Array:", arr10)

sorted_desc = np.sort(arr10)[::-1]
print("Sorted descending:", sorted_desc)

arr11 = np.arange(1, 26).reshape(5, 5)
print("Array:\n", arr11)

subset = arr11[:3, 1:4]  # rows 0-2, columns 1-3
print("Subset:\n", subset)


arr12 = np.random.rand(10)
sorted_arr12 = np.sort(arr12)
print("Sorted Array:", sorted_arr12)

value = 0.5
index = np.searchsorted(sorted_arr12, value)
print(f"Index to insert {value}:", index)


arr13 = np.random.randint(0, 10, 8)
print("Array:", arr13)

unique_sorted = np.sort(np.unique(arr13))
print("Unique sorted values:", unique_sorted)












Array: [38  7 68 21 76 92 77 57 65 20 82 74 75 61 55]
Values > 50: [68 76 92 77 57 65 82 74 75 61 55]
Array: [ 2  4  6  8 10 12 14 16 18 20 22 24 26 28 30 32 34 36 38 40]
Every third element: [ 2  8 14 20 26 32 38]
Array:
 [[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]
 [13 14 15 16]]
Elements > 10: [11 12 13 14 15 16]
Original Array: [0 5 5 6 5 5 6 1 0 8]
After replacement: [0 5 5 6 5 5 6 0 0 8]
Array:
 [[ 1  2  3  4  5  6]
 [ 7  8  9 10 11 12]
 [13 14 15 16 17 18]
 [19 20 21 22 23 24]
 [25 26 27 28 29 30]
 [31 32 33 34 35 36]]
Rows 1, 3, 5:
 [[ 1  2  3  4  5  6]
 [13 14 15 16 17 18]
 [25 26 27 28 29 30]]
Array: [93 80 85 93 88 68 24 26 28  1]
Labels: ['High' 'High' 'High' 'High' 'High' 'High' 'Low' 'Low' 'Low' 'Low']
Array:
 [[44 24 14]
 [43 19 30]
 [34 15 35]]
Index of maximum value: (np.int64(0), np.int64(0))
Array: [10 27  8  9 15 29 27  3  7 14 19 21]
Size Labels: ['Medium' 'Large' 'Small' 'Small' 'Medium' 'Large' 'Large' 'Small' 'Small'
 'Medium' 'Medium' 'Large']
Array: [-9 -1  1