In [1]:
import numpy as np

# 1. Create two 2D arrays and stack vertically
arr1 = np.random.randint(0, 10, (3, 4))  # shape (3, 4)
arr2 = np.random.randint(0, 10, (3, 4))  # shape (3, 4)

v_stack = np.vstack((arr1, arr2))  # shape (6, 4)

print("Array 1:\n", arr1)
print("\nArray 2:\n", arr2)
print("\nVertically Stacked (6x4):\n", v_stack)


# 2. Horizontally stack two 2D arrays
h_stack = np.hstack((arr1, arr2))  # shape (3, 8)
print("\nHorizontally Stacked (3x8):\n", h_stack)


# 3. Stack along the third axis (depth) using dstack
d_stack = np.dstack((arr1, arr2))  # shape (3, 4, 2)
print("\nStacked along 3rd axis (3x4x2):\n", d_stack)


# 4. Split a 2D array into two equal parts
arr3 = np.random.randint(0, 10, (6, 4))  # shape (6, 4)
split_arr = np.split(arr3, 2)  # splits into two (3, 4) arrays

print("\nOriginal 6x4 Array:\n", arr3)
print("\nAfter Splitting into 2 arrays (each 3x4):")
for i, part in enumerate(split_arr, 1):
    print(f"Part {i}:\n", part)


Array 1:
 [[5 5 0 8]
 [6 4 4 0]
 [4 1 0 9]]

Array 2:
 [[1 6 8 2]
 [8 7 4 2]
 [5 8 4 1]]

Vertically Stacked (6x4):
 [[5 5 0 8]
 [6 4 4 0]
 [4 1 0 9]
 [1 6 8 2]
 [8 7 4 2]
 [5 8 4 1]]

Horizontally Stacked (3x8):
 [[5 5 0 8 1 6 8 2]
 [6 4 4 0 8 7 4 2]
 [4 1 0 9 5 8 4 1]]

Stacked along 3rd axis (3x4x2):
 [[[5 1]
  [5 6]
  [0 8]
  [8 2]]

 [[6 8]
  [4 7]
  [4 4]
  [0 2]]

 [[4 5]
  [1 8]
  [0 4]
  [9 1]]]

Original 6x4 Array:
 [[9 6 6 6]
 [8 2 5 1]
 [6 9 4 2]
 [3 2 7 0]
 [2 3 6 0]
 [8 8 5 0]]

After Splitting into 2 arrays (each 3x4):
Part 1:
 [[9 6 6 6]
 [8 2 5 1]
 [6 9 4 2]]
Part 2:
 [[3 2 7 0]
 [2 3 6 0]
 [8 8 5 0]]


In [2]:
# 5. Split a 2D array into 3 parts using np.array_split()
arr = np.random.randint(0, 10, (7, 4))  # shape (7, 4)
split_arr = np.array_split(arr, 3, axis=0)  # split along rows (axis=0)

print("Original 7x4 Array:\n", arr)
print("\nAfter Splitting into 3 parts:")
for i, part in enumerate(split_arr, 1):
    print(f"Part {i} (shape {part.shape}):\n", part)


# 6. Create a 3D array and transpose using .T
arr3d = np.random.randint(0, 10, (2, 3, 4))  # shape (2, 3, 4)
transposed_T = arr3d.T  # automatic transpose (reverses axes)
print("\nOriginal Shape:", arr3d.shape)
print("Transposed using .T Shape:", transposed_T.shape)
print("\nTransposed Array (.T):\n", transposed_T)


# 7. Transpose a 3D array with np.transpose()
arr3d_2 = np.random.randint(0, 10, (2, 3, 4))  # shape (2, 3, 4)
transposed_np = np.transpose(arr3d_2, (2, 1, 0))  # reorder axes → (4, 3, 2)

print("\nOriginal Shape:", arr3d_2.shape)
print("Transposed using np.transpose Shape:", transposed_np.shape)
print("\nTransposed Array (np.transpose):\n", transposed_np)


Original 7x4 Array:
 [[1 1 1 4]
 [5 0 8 6]
 [1 9 2 9]
 [7 9 9 3]
 [6 8 9 3]
 [0 5 6 7]
 [2 3 6 4]]

After Splitting into 3 parts:
Part 1 (shape (3, 4)):
 [[1 1 1 4]
 [5 0 8 6]
 [1 9 2 9]]
Part 2 (shape (2, 4)):
 [[7 9 9 3]
 [6 8 9 3]]
Part 3 (shape (2, 4)):
 [[0 5 6 7]
 [2 3 6 4]]

Original Shape: (2, 3, 4)
Transposed using .T Shape: (4, 3, 2)

Transposed Array (.T):
 [[[7 8]
  [1 9]
  [9 4]]

 [[5 8]
  [8 9]
  [8 6]]

 [[6 5]
  [6 9]
  [5 5]]

 [[6 9]
  [9 5]
  [1 3]]]

Original Shape: (2, 3, 4)
Transposed using np.transpose Shape: (4, 3, 2)

Transposed Array (np.transpose):
 [[[4 1]
  [9 9]
  [2 2]]

 [[8 1]
  [5 7]
  [4 0]]

 [[1 3]
  [5 0]
  [5 6]]

 [[9 7]
  [0 5]
  [5 6]]]


In [3]:
# 8. Swap the axes of a 3D array using np.swapaxes()
arr3d = np.random.randint(0, 10, (2, 3, 4))  # shape (2, 3, 4)
swapped = np.swapaxes(arr3d, 0, 2)  # swap axis 0 and 2 -> (4, 3, 2)

print("Original Shape:", arr3d.shape)
print("Swapped Shape:", swapped.shape)
print("\nSwapped Array (axis 0 <-> 2):\n", swapped)


# 9. Slice a 3D array to extract a 2D array
arr3d_slice = np.random.randint(0, 10, (5, 3, 4))  # shape (5, 3, 4)
slice_2d = arr3d_slice[2, :, :]  # take index 2 along first axis -> shape (3, 4)

print("\nOriginal Shape:", arr3d_slice.shape)
print("Sliced 2D Array Shape:", slice_2d.shape)
print("Sliced 2D Array (time index 2):\n", slice_2d)


# 10. Horizontal stacking with arrays of different sizes
arrA = np.random.randint(0, 10, (3, 4))  # shape (3, 4)
arrB = np.random.randint(0, 10, (3, 2))  # shape (3, 2)

try:
    h_stack = np.hstack((arrA, arrB))  # works if row counts match
    print("\nArray A (3x4):\n", arrA)
    print("\nArray B (3x2):\n", arrB)
    print("\nHorizontally Stacked (3x6):\n", h_stack)
except ValueError as e:
    print("\nError in stacking:", e)


Original Shape: (2, 3, 4)
Swapped Shape: (4, 3, 2)

Swapped Array (axis 0 <-> 2):
 [[[3 5]
  [8 9]
  [6 4]]

 [[3 8]
  [6 4]
  [0 0]]

 [[2 9]
  [5 7]
  [3 4]]

 [[6 1]
  [5 0]
  [6 9]]]

Original Shape: (5, 3, 4)
Sliced 2D Array Shape: (3, 4)
Sliced 2D Array (time index 2):
 [[3 4 8 9]
 [9 0 6 1]
 [7 9 7 2]]

Array A (3x4):
 [[2 1 0 2]
 [2 4 5 0]
 [2 4 8 8]]

Array B (3x2):
 [[3 2]
 [2 9]
 [5 1]]

Horizontally Stacked (3x6):
 [[2 1 0 2 3 2]
 [2 4 5 0 2 9]
 [2 4 8 8 5 1]]


In [4]:
# 11. Stack multiple 1D arrays vertically using np.vstack()
arr1 = np.array([1, 2, 3, 4])  # shape (4,)
arr2 = np.array([5, 6, 7, 8])  # shape (4,)
arr3 = np.array([9, 10, 11, 12])  # shape (4,)

v_stack_1d = np.vstack((arr1, arr2, arr3))  # shape (3, 4)

print("11. Vertically Stacked 1D Arrays (3x4):\n", v_stack_1d)


# 12. Stack two 2D arrays horizontally using np.hstack()
A = np.random.randint(0, 10, (3, 3))  # shape (3, 3)
B = np.random.randint(0, 10, (3, 3))  # shape (3, 3)

h_stack_2d = np.hstack((A, B))  # shape (3, 6)

print("\n12. Array A (3x3):\n", A)
print("Array B (3x3):\n", B)
print("Horizontally Stacked (3x6):\n", h_stack_2d)


# 13. Split a 1D array into 4 equal parts
arr1d = np.arange(1, 13)  # 1D array size 12 → [1,2,...,12]
split_parts = np.split(arr1d, 4)  # 4 equal parts of size 3

print("\n13. Original 1D Array (size 12):\n", arr1d)
print("Split into 4 equal parts:")
for i, part in enumerate(split_parts, 1):
    print(f"Part {i} (shape {part.shape}): {part}")


11. Vertically Stacked 1D Arrays (3x4):
 [[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]]

12. Array A (3x3):
 [[3 4 0]
 [0 5 1]
 [2 4 6]]
Array B (3x3):
 [[2 5 6]
 [3 7 4]
 [7 3 9]]
Horizontally Stacked (3x6):
 [[3 4 0 2 5 6]
 [0 5 1 3 7 4]
 [2 4 6 7 3 9]]

13. Original 1D Array (size 12):
 [ 1  2  3  4  5  6  7  8  9 10 11 12]
Split into 4 equal parts:
Part 1 (shape (3,)): [1 2 3]
Part 2 (shape (3,)): [4 5 6]
Part 3 (shape (3,)): [7 8 9]
Part 4 (shape (3,)): [10 11 12]
