In [ ]:
import numpy as np
sales_data = np.zeros((3, 4), dtype=int)

sales_data = np.full((3, 4), [100, 150, 200, 250], dtype=int)


reshaped_sales_data = sales_data.reshape(4, 3) 


random_sales_data = np.random.randint(50, 200, size=(3, 4)) 
print(random_sales_data)

sales_data_copy = random_sales_data.copy() 
sales_data_copy[0, 0] = 999 
print("Original Sales Data:\n", random_sales_data) 
print("Modified Sales Data Copy:\n", sales_data_copy)

sliced_data = random_sales_data[:1, :3] 
print(sliced_data)

[[ 58 188 139  84]
 [171 156  51 154]
 [ 73 134 164 104]]
Original Sales Data:
 [[ 58 188 139  84]
 [171 156  51 154]
 [ 73 134 164 104]]
Modified Sales Data Copy:
 [[999 188 139  84]
 [171 156  51 154]
 [ 73 134 164 104]]
[[ 58 188 139]]
