In [1]:
import numpy as np

temperature_data = np.ones((5, 30), dtype=int) * 23


temperature_data = np.full((5, 30), 25)
temperature_data[0] = np.random.randint(20, 27, size=30) 
temperature_data[1,:3] = np.random.randint(100, 200, size=3)


reshape_temparature_data = temperature_data.reshape(30, 5)
print(reshape_temparature_data)

slicing = reshape_temparature_data[2:6 , :] 
print(slicing)

[[ 23  25  21  23  23]
 [ 21  24  21  21  26]
 [ 24  20  23  24  24]
 [ 24  26  20  22  26]
 [ 20  25  22  23  22]
 [ 26  22  21  22  20]
 [165 195 114  25  25]
 [ 25  25  25  25  25]
 [ 25  25  25  25  25]
 [ 25  25  25  25  25]
 [ 25  25  25  25  25]
 [ 25  25  25  25  25]
 [ 25  25  25  25  25]
 [ 25  25  25  25  25]
 [ 25  25  25  25  25]
 [ 25  25  25  25  25]
 [ 25  25  25  25  25]
 [ 25  25  25  25  25]
 [ 25  25  25  25  25]
 [ 25  25  25  25  25]
 [ 25  25  25  25  25]
 [ 25  25  25  25  25]
 [ 25  25  25  25  25]
 [ 25  25  25  25  25]
 [ 25  25  25  25  25]
 [ 25  25  25  25  25]
 [ 25  25  25  25  25]
 [ 25  25  25  25  25]
 [ 25  25  25  25  25]
 [ 25  25  25  25  25]]
[[24 20 23 24 24]
 [24 26 20 22 26]
 [20 25 22 23 22]
 [26 22 21 22 20]]
