In [ ]:
import numpy as np

grades = np.zeros((5, 4), dtype=int)
print("Initial grades (all zeros):\n", grades)

grades = np.random.randint(50, 101, size=(5, 4))
print("\nRandom student grades:\n", grades)

max_grades = np.full((1, 4), 100)  
print("\nMaximum grades per subject:\n", max_grades)


grades_reshaped = grades.reshape(5, 2, 2)  # 5 students, 2 semesters, 2 subjects per semester
print("\nGrades reshaped for 2 semesters:\n", grades_reshaped)

improved_grades = grades.copy()
improved_grades += 5  # add 5 points to all grades
print("\nImproved grades:\n", improved_grades)

second_student_grades = grades[1, :]
print("\nGrades of second student:\n", second_student_grades)

third_subject_grades = grades[:, 2]
print("\nGrades of third subject for all students:\n", third_subject_grades)


Initial grades (all zeros):
 [[0 0 0 0]
 [0 0 0 0]
 [0 0 0 0]
 [0 0 0 0]
 [0 0 0 0]]

Random student grades:
 [[ 68  53  84  74]
 [ 84  76  57  65]
 [ 97  71  97  63]
 [ 54  73  99  89]
 [ 86  80  62 100]]

Maximum grades per subject:
 [[100 100 100 100]]

Grades reshaped for 2 semesters:
 [[[ 68  53]
  [ 84  74]]

 [[ 84  76]
  [ 57  65]]

 [[ 97  71]
  [ 97  63]]

 [[ 54  73]
  [ 99  89]]

 [[ 86  80]
  [ 62 100]]]

Improved grades:
 [[ 73  58  89  79]
 [ 89  81  62  70]
 [102  76 102  68]
 [ 59  78 104  94]
 [ 91  85  67 105]]

Grades of second student:
 [84 76 57 65]

Grades of third subject for all students:
 [84 57 97 99 62]
