In [ ]:
import numpy as np

sales_data = np.ones((3, 7), dtype=int)
print("Initial sales data (all ones):\n", sales_data)

# 2. Modify the array with realistic random sales between 10 and 50
sales_data = np.random.randint(10, 51, size=(3, 7))
print("\nRandomized sales data:\n", sales_data)

# 3. Generate array of days (1 to 7) and reshape into 3x7
days_of_week = np.arange(1, 8)  # 1D array [1 2 3 4 5 6 7]
days_matrix = np.tile(days_of_week, (3, 1))  # replicate for 3 products
print("\nDays of the week matrix:\n", days_matrix)

# 4. Flatten the sales data using ravel() and flatten()
flattened_ravel = sales_data.ravel()
flattened_flatten = sales_data.flatten()
print("\nSales data flattened with ravel():\n", flattened_ravel)
print("\nSales data flattened with flatten():\n", flattened_flatten)

# 5. Clone sales data and simulate discount/boost
sales_clone = sales_data.copy()
sales_clone = sales_clone + 5  # boost sales by 5 units
print("\nSales data after boost (clone):\n", sales_clone)

# 6. Slice the first 3 days of sales for all products (first 3 columns)
first_3_days_sales = sales_data[:, :3]
print("\nSales data for first 3 days:\n", first_3_days_sales)


Initial sales data (all ones):
 [[1 1 1 1 1 1 1]
 [1 1 1 1 1 1 1]
 [1 1 1 1 1 1 1]]

Randomized sales data:
 [[20 27 40 43 32 46 31]
 [25 10 47 26 43 15 31]
 [15 43 29 35 32 46 44]]

Days of the week matrix:
 [[1 2 3 4 5 6 7]
 [1 2 3 4 5 6 7]
 [1 2 3 4 5 6 7]]

Sales data flattened with ravel():
 [20 27 40 43 32 46 31 25 10 47 26 43 15 31 15 43 29 35 32 46 44]

Sales data flattened with flatten():
 [20 27 40 43 32 46 31 25 10 47 26 43 15 31 15 43 29 35 32 46 44]

Sales data after boost (clone):
 [[25 32 45 48 37 51 36]
 [30 15 52 31 48 20 36]
 [20 48 34 40 37 51 49]]

Sales data for first 3 days:
 [[20 27 40]
 [25 10 47]
 [15 43 29]]
