In [4]:
import numpy as np
arr=np.zeros((3,3))
print(arr)

[[0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]]


In [ ]:
arr=np.ones((5,5),dtype=float)
print(arr)

[[1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]]


In [ ]:
arr=np.full((4,4),7)
print(arr)

[[7 7 7 7]
 [7 7 7 7]
 [7 7 7 7]
 [7 7 7 7]]


In [ ]:
arr=np.eye(4,k=2,dtype=int)
print(arr)

[[0 0 1 0]
 [0 0 0 1]
 [0 0 0 0]
 [0 0 0 0]]


In [ ]:
import numpy as np
arange=np.arange(10,50,5)
print(arange)

arr = np.linspace(0, 1, 100)
print(arr)


In [ ]:
random=np.random.rand(10,20)
print(random)

random_normal= np.random.randn(3, 3)
print(random_normal)



In [ ]:
random_integers = np.random.randint(10, 50, size=(3, 3))
print(random_integers)

arr = np.arange(1, 13)  
print("\nOriginal 1D array:")
print(arr)

reshaped_matrix = arr.reshape(3, 4)
print("\nReshaped 3x4 matrix:")
print(reshaped_matrix)



In [42]:


matrix = np.array([[1, 2, 3],
                   [4, 5, 6],
                   [7, 8, 9]])

# Using ravel()
flattened_ravel = matrix.ravel()
print("Flattened using ravel():", flattened_ravel)

# Using flatten()
flattened_flatten = matrix.flatten()
print("Flattened using flatten():", flattened_flatten)


Flattened using ravel(): [1 2 3 4 5 6 7 8 9]
Flattened using flatten(): [1 2 3 4 5 6 7 8 9]


In [44]:
original = np.array([1, 2, 3])
cloned = original.copy()

# Modify original
original[0] = 100

print("Original array:", original)
print("Cloned array:  ", cloned)

matrix = np.array([[1, 2, 3],
                   [4, 5, 6],
                   [7, 8, 9]])

second_row = matrix[1, :]  
print("Second row:", second_row)


Original array: [100   2   3]
Cloned array:   [1 2 3]
Second row: [4 5 6]
