In [1]:
import numpy as np

# 1. Data Representation
# a. Create a 5x12 array representing stock prices for 5 stocks over 12 months
np.random.seed(42)  # for reproducible results
stock_prices = np.random.randint(100, 501, size=(5, 12))
print("Stock Prices (5 stocks x 12 months):\n", stock_prices)

# 2. Element-wise Operations
# a. Calculate percentage change from one month to the next
# (current_month - previous_month) / previous_month * 100
percentage_change = (stock_prices[:, 1:] - stock_prices[:, :-1]) / stock_prices[:, :-1] * 100
print("\nPercentage change month-to-month:\n", percentage_change)

# 3. Broadcasting
# a. Subtract the average stock price across all months from each stock's price
row_means = np.mean(stock_prices, axis=1, keepdims=True)  # shape (5,1) for broadcasting
price_minus_mean = stock_prices - row_means
print("\nStock prices minus row-wise mean (broadcasted):\n", price_minus_mean)

# 4. Universal Functions (ufunc)
# a. Volatility (using sqrt of variance for each stock)
volatility = np.sqrt(np.var(stock_prices, axis=1))
print("\nVolatility (std deviation) for each stock:", volatility)

# b. Simulate price growth over time using np.exp()
exp_growth = np.exp(stock_prices / 500)  # scaled to avoid very large numbers
print("\nExponential growth simulation:\n", exp_growth)

# c. Logarithmic scale of stock prices
log_prices = np.log10(stock_prices)
print("\nLogarithmic scale of stock prices:\n", log_prices)

# 5. Aggregation Functions
# a. Mean and median stock price across months for each stock
mean_prices = np.mean(stock_prices, axis=1)
median_prices = np.median(stock_prices, axis=1)
print("\nMean stock price per stock:", mean_prices)
print("Median stock price per stock:", median_prices)

# b. Maximum and minimum stock price across months for each stock
max_prices = np.max(stock_prices, axis=1)
min_prices = np.min(stock_prices, axis=1)
print("\nMaximum stock price per stock:", max_prices)
print("Minimum stock price per stock:", min_prices)

# c. Variance and standard deviation to analyze fluctuations
variance_prices = np.var(stock_prices, axis=1)
std_prices = np.std(stock_prices, axis=1)
print("\nVariance of stock prices per stock:", variance_prices)
print("Standard deviation of stock prices per stock:", std_prices)


Stock Prices (5 stocks x 12 months):
 [[202 448 370 206 171 288 120 202 221 314 430 187]
 [472 199 459 251 230 249 408 357 443 393 485 291]
 [376 260 413 121 352 335 444 148 158 269 287 370]
 [289 274 150 463 154 343 419 230 406 234 120 428]
 [266 373 487 188 415 113 341 364 445 152 485 439]]

Percentage change month-to-month:
 [[121.78217822 -17.41071429 -44.32432432 -16.99029126  68.42105263
  -58.33333333  68.33333333   9.40594059  42.08144796  36.94267516
  -56.51162791]
 [-57.83898305 130.65326633 -45.31590414  -8.36653386   8.26086957
   63.85542169 -12.5         24.08963585 -11.28668172  23.40966921
  -40.        ]
 [-30.85106383  58.84615385 -70.70217918 190.90909091  -4.82954545
   32.53731343 -66.66666667   6.75675676  70.25316456   6.69144981
   28.91986063]
 [ -5.19031142 -45.25547445 208.66666667 -66.73866091 122.72727273
   22.1574344  -45.10739857  76.52173913 -42.36453202 -48.71794872
  256.66666667]
 [ 40.22556391  30.56300268 -61.3963039  120.74468085 -72.77108434
  2