In [19]:
import numpy as np

# Temperature data (°C) for 3 cities over 7 days
temperature = np.array([
    [30, 32, 31, 29, 28, 27, 30],   
    [25, 26, 27, 28, 29, 30, 31],   
    [20, 21, 22, 23, 24, 25, 26]    
])

# Humidity data (%) for 3 cities over 7 days
humidity = np.array([
    [60, 62, 58, 55, 65, 70, 68],  
    [50, 52, 55, 53, 56, 58, 60],   
    [45, 48, 47, 50, 52, 55, 57]    
])

# Wind speed data (m/s) for 3 cities over 7 days
wind_speed = np.array([
    [5, 6, 7, 5, 4, 6, 5],       
    [3, 4, 5, 4, 3, 4, 5],          
    [2, 3, 2, 3, 4, 3, 2]          
])

print("Temperature (°C):\n", temperature)
print("\nHumidity (%):\n", humidity)
print("\nWind Speed (m/s):\n", wind_speed)


# a. Element-wise addition (temperature + wind_speed)
perceived_temp = np.add(temperature , wind_speed)
print("\nPerceived Temperature (Temp + Wind Speed):\n", perceived_temp)

# b. Subtract humidity from temperature
temp_minus_humidity = np.subtract(temperature,humidity)
print("\nTemperature - Humidity:\n", temp_minus_humidity)






Temperature (°C):
 [[30 32 31 29 28 27 30]
 [25 26 27 28 29 30 31]
 [20 21 22 23 24 25 26]]

Humidity (%):
 [[60 62 58 55 65 70 68]
 [50 52 55 53 56 58 60]
 [45 48 47 50 52 55 57]]

Wind Speed (m/s):
 [[5 6 7 5 4 6 5]
 [3 4 5 4 3 4 5]
 [2 3 2 3 4 3 2]]

Perceived Temperature (Temp + Wind Speed):
 [[35 38 38 34 32 33 35]
 [28 30 32 32 32 34 36]
 [22 24 24 26 28 28 28]]

Temperature - Humidity:
 [[-30 -30 -27 -26 -37 -43 -38]
 [-25 -26 -28 -25 -27 -28 -29]
 [-25 -27 -25 -27 -28 -30 -31]]


In [20]:
threshold = 30
# a. Subtract threshold using broadcasting
temp_above_threshold = np.subtract(temperature,threshold)
print("Temperature - Threshold (30°C):\n", temp_above_threshold)
print(temp_above_threshold)

# Identify which values are above the threshold
above_mask = temperature > threshold
print("\nCities/Days Above 30°C:\n", above_mask)

Temperature - Threshold (30°C):
 [[  0   2   1  -1  -2  -3   0]
 [ -5  -4  -3  -2  -1   0   1]
 [-10  -9  -8  -7  -6  -5  -4]]
[[  0   2   1  -1  -2  -3   0]
 [ -5  -4  -3  -2  -1   0   1]
 [-10  -9  -8  -7  -6  -5  -4]]

Cities/Days Above 30°C:
 [[False  True  True False False False False]
 [False False False False False False  True]
 [False False False False False False False]]


In [21]:
# a. Square root of wind speed (simulated reduction)
sqrt_wind = np.sqrt(wind_speed)
print("√ Wind Speed:\n", sqrt_wind)

# b. Logarithm (base 10) of humidity
log_humidity = np.log10(humidity)
print("\nlog10(Humidity):\n", log_humidity)

# c. Sine of temperature (simulate seasonal variation)
seasonal_temp = np.sin(temperature)
print("\nSin(Temperature):\n", seasonal_temp)

√ Wind Speed:
 [[2.23606798 2.44948974 2.64575131 2.23606798 2.         2.44948974
  2.23606798]
 [1.73205081 2.         2.23606798 2.         1.73205081 2.
  2.23606798]
 [1.41421356 1.73205081 1.41421356 1.73205081 2.         1.73205081
  1.41421356]]

log10(Humidity):
 [[1.77815125 1.79239169 1.76342799 1.74036269 1.81291336 1.84509804
  1.83250891]
 [1.69897    1.71600334 1.74036269 1.72427587 1.74818803 1.76342799
  1.77815125]
 [1.65321251 1.68124124 1.67209786 1.69897    1.71600334 1.74036269
  1.75587486]]

Sin(Temperature):
 [[-0.98803162  0.55142668 -0.40403765 -0.66363388  0.27090579  0.95637593
  -0.98803162]
 [-0.13235175  0.76255845  0.95637593  0.27090579 -0.66363388 -0.98803162
  -0.40403765]
 [ 0.91294525  0.83665564 -0.00885131 -0.8462204  -0.90557836 -0.13235175
   0.76255845]]


In [ ]:
# a. Mean & Median temperature across all cities (per day → axis=0)
mean_temp_per_day = np.mean(temperature, axis=0)
median_temp_per_day = np.median(temperature, axis=0)

print("Mean Temperature per Day:\n", mean_temp_per_day)
print("\nMedian Temperature per Day:\n", median_temp_per_day)

# b. Max wind speed and index
max_wind = np.max(wind_speed)
max_wind_index = np.argmax(wind_speed)  # flattened index
max_wind_position = np.unravel_index(max_wind_index, wind_speed.shape)

print("\nMax Wind Speed:", max_wind)
print("Index of Max Wind Speed (flattened):", max_wind_index)
print("Position (City, Day):", max_wind_position)
 c. Variance & Standard Deviation of humidity (per city → axis=1)
variance_humidity = np.var(humidity, axis=1)
stddev_humidity = np.std(humidity, axis=1)

print("\nVariance of Humidity per City:\n", variance_humidity)
print("\nStandard Deviation of Humidity per City:\n", stddev_humidity)

Mean Temperature per Day:
 [25.         26.33333333 26.66666667 26.66666667 27.         27.33333333
 29.        ]

Median Temperature per Day:
 [25. 26. 27. 28. 28. 27. 30.]

Max Wind Speed: 7
Index of Max Wind Speed (flattened): 2
Position (City, Day): (np.int64(0), np.int64(2))

Variance of Humidity per City:
 [25.10204082 10.40816327 16.24489796]

Standard Deviation of Humidity per City:
 [5.01019369 3.22616851 4.03049599]
