In [1]:
import numpy as np

# Create two 1D arrays of the same length
arr1 = np.array([10, 20, 30, 40, 50])
arr2 = np.array([2, 4, 6, 8, 10])

# Element-wise addition
addition = np.add(arr1,arr2)
print("Addition:", addition)

# Element-wise subtraction
subtraction = np.subtract(arr1,arr2)
print("Subtraction:", subtraction)

# Element-wise multiplication
multiplication = np.multiply(arr1,arr2)
print("Multiplication:", multiplication)

# Element-wise division
division =np.divide(arr1,arr2) 
print("Division:", division)


Addition: [12 24 36 48 60]
Subtraction: [ 8 16 24 32 40]
Multiplication: [ 20  80 180 320 500]
Division: [5. 5. 5. 5. 5.]


In [3]:
# Create a 2D array (3x3)
arr2d = np.array([
    [1, 2, 3],
    [4, 5, 6],
    [7, 8, 9]
])

# Create a 1D array (length 3)
arr1d = np.array([10, 20, 30])

# Use broadcasting to add the 1D array to each row of the 2D array
result = arr2d + arr1d
print("Original 2D Array:\n", arr2d)
print("\n1D Array:\n", arr1d)
print("\nResult after Broadcasting Addition:\n", result)

Original 2D Array:
 [[1 2 3]
 [4 5 6]
 [7 8 9]]

1D Array:
 [10 20 30]

Result after Broadcasting Addition:
 [[11 22 33]
 [14 25 36]
 [17 28 39]]


In [12]:
import numpy as np

# Create two 1D arrays
arr1 = np.array([5, 10, 15, 20])
arr2 = np.array([2, 4, 6, 8])
print("Array1:",arr1)
print("Array2:",arr2)

# Element-wise addition using np.add()
add_ufunc = np.add(arr1, arr2)
print("\nUsing np.add():", add_ufunc)

# Element-wise addition using the + operator
add_operator = arr1 + arr2
print("Using + operator:", add_operator)

# Verify if they are equal
print("Are both results equal?", np.array_equal(add_ufunc, add_operator))

# Element-wise subtraction using np.subtract()
sub_ufunc = np.subtract(arr1, arr2)
print("\nUsing np.subtract():", sub_ufunc)

# Element-wise subtraction using the - operator
sub_operator = arr1 - arr2
print("Using - operator:", sub_operator)

# Verify if both results are equal
print("Are both results equal?", np.array_equal(sub_ufunc, sub_operator))

# Element-wise multiplication using np.multiply()
mul_ufunc = np.multiply(arr1, arr2)
print("\nUsing np.multiply():", mul_ufunc)

# Element-wise multiplication using the * operator
mul_operator = arr1 * arr2
print("Using * operator:", mul_operator)

# Verify if both results are equal
print("Are both results equal?", np.array_equal(mul_ufunc, mul_operator))

# Create two 1D arrays (note one zero to demonstrate safety)
array1 = np.array([10, 20, 30, 40])
array2 = np.array([2, 0, 5, 0])  # divisor has zeros

# Add a small constant to divisor to avoid division by zero
safe_divisor = array2 + 1e-10

# Element-wise division using np.divide()
div_ufunc = np.divide(array1, safe_divisor)
print("\nUsing np.divide() with safety:\n", div_ufunc)

# Compare with / operator (also safe)
div_operator = array1 / safe_divisor
print("Using / operator with safety:\n", div_operator)

# Verify equality
print("Are both results equal?", np.allclose(div_ufunc, div_operator))


Array1: [ 5 10 15 20]
Array2: [2 4 6 8]

Using np.add(): [ 7 14 21 28]
Using + operator: [ 7 14 21 28]
Are both results equal? True

Using np.subtract(): [ 3  6  9 12]
Using - operator: [ 3  6  9 12]
Are both results equal? True

Using np.multiply(): [ 10  40  90 160]
Using * operator: [ 10  40  90 160]
Are both results equal? True

Using np.divide() with safety:
 [5.e+00 2.e+11 6.e+00 4.e+11]
Using / operator with safety:
 [5.e+00 2.e+11 6.e+00 4.e+11]
Are both results equal? True


In [ ]:
# Create two 1D arrays
arr1 = np.array([10, 15, 20, 25])
arr2 = np.array([3, 4, 0, 6])  # Note: 0 included to handle division by zero

# To avoid division by zero, replace zeros with a small constant
safe_divisor = arr2 + 1e-10

# np.mod() vs % operator
mod_result_ufunc = np.mod(arr1, safe_divisor)
mod_result_operator = arr1 % safe_divisor

print("Modulus using np.mod():", mod_result_ufunc)
print("Modulus using % operator:", mod_result_operator)

Modulus using np.mod(): [1.00000000e+00 3.00000000e+00 9.99992714e-11 1.00000000e+00]
Modulus using % operator: [1.00000000e+00 3.00000000e+00 9.99992714e-11 1.00000000e+00]


In [14]:
# 8. np.exp() - Exponential function
arr_exp = np.array([0, 1, 2, 3])
exp_result = np.exp(arr_exp)
print("Exponential of each element (e^x):", exp_result)

# 9. np.sqrt() - Square root function
# Ensure non-negative values
arr_sqrt = np.array([0, 4, 9, 16])
sqrt_result = np.sqrt(arr_sqrt)
print("Square root of each element:", sqrt_result)


Exponential of each element (e^x): [ 1.          2.71828183  7.3890561  20.08553692]
Square root of each element: [0. 2. 3. 4.]


In [15]:
# 10. np.log() - Natural logarithm
arr_log = np.array([1, 2.718, 7.389, 20])  # all positive values
log_result = np.log(arr_log)
print("Natural logarithm (ln) of each element:", log_result)

# 11. np.log10() - Base-10 logarithm
arr_log10 = np.array([1, 10, 100, 1000])  # all positive values
log10_result = np.log10(arr_log10)
print("Base-10 logarithm of each element:", log10_result)


Natural logarithm (ln) of each element: [0.         0.99989632 1.99999241 2.99573227]
Base-10 logarithm of each element: [0. 1. 2. 3.]


In [16]:
# 12 Create a 1D array of angles in radians
angles = np.array([0, np.pi/6, np.pi/4, np.pi/3, np.pi/2])

# Compute trigonometric values
sin_values = np.sin(angles)
cos_values = np.cos(angles)
tan_values = np.tan(angles)

# Print results
print("Angles (radians):", angles)
print("Sine values:", sin_values)
print("Cosine values:", cos_values)
print("Tangent values:", tan_values)


Angles (radians): [0.         0.52359878 0.78539816 1.04719755 1.57079633]
Sine values: [0.         0.5        0.70710678 0.8660254  1.        ]
Cosine values: [1.00000000e+00 8.66025404e-01 7.07106781e-01 5.00000000e-01
 6.12323400e-17]
Tangent values: [0.00000000e+00 5.77350269e-01 1.00000000e+00 1.73205081e+00
 1.63312394e+16]


In [17]:
#13 Create a 2D array of random integers between 1 and 20, shape (3, 4)
arr = np.random.randint(1, 21, size=(3, 4))
print("2D Array:\n", arr)

# 1. Sum of all elements
total_sum = np.sum(arr)
print("\nSum of all elements:", total_sum)

# 2. Mean value of the array
mean_value = np.mean(arr)
print("Mean value:", mean_value)

# 3. Minimum value in each column
min_columns = np.min(arr, axis=0)
print("Minimum value in each column:", min_columns)

# 4. Maximum value in each row
max_rows = np.max(arr, axis=1)
print("Maximum value in each row:", max_rows)


2D Array:
 [[ 3 19  3 17]
 [10  2 15  7]
 [18 13  5 19]]

Sum of all elements: 131
Mean value: 10.916666666666666
Minimum value in each column: [3 2 3 7]
Maximum value in each row: [19 15 19]
