In [2]:
import numpy as np

# Seed for reproducibility
np.random.seed(42)

# a. Create a 5x12 array (5 products, 12 months)
sales_data = np.random.randint(100, 501, size=(5, 12))

print("Sales Data (Units Sold):\n", sales_data)


Sales Data (Units Sold):
 [[202 448 370 206 171 288 120 202 221 314 430 187]
 [472 199 459 251 230 249 408 357 443 393 485 291]
 [376 260 413 121 352 335 444 148 158 269 287 370]
 [289 274 150 463 154 343 419 230 406 234 120 428]
 [266 373 487 188 415 113 341 364 445 152 485 439]]


In [3]:
# a. Yearly sales for each product (sum across months → axis=1)
yearly_sales = np.sum(sales_data, axis=1)
print("\nYearly Sales per Product:\n", yearly_sales)

# b. Monthly growth for each product (difference between consecutive months)
monthly_growth = np.diff(sales_data, axis=1)
print("\nMonthly Growth per Product:\n", monthly_growth)


Yearly Sales per Product:
 [3159 4237 3533 3510 4068]

Monthly Growth per Product:
 [[ 246  -78 -164  -35  117 -168   82   19   93  116 -243]
 [-273  260 -208  -21   19  159  -51   86  -50   92 -194]
 [-116  153 -292  231  -17  109 -296   10  111   18   83]
 [ -15 -124  313 -309  189   76 -189  176 -172 -114  308]
 [ 107  114 -299  227 -302  228   23   81 -293  333  -46]]


In [6]:
# a. Apply 10% discount (multiply by 0.9)
discounted_sales = sales_data * 0.9
print("\nSales Data after 10% Discount:\n", discounted_sales)


Sales Data after 10% Discount:
 [[181.8 403.2 333.  185.4 153.9 259.2 108.  181.8 198.9 282.6 387.  168.3]
 [424.8 179.1 413.1 225.9 207.  224.1 367.2 321.3 398.7 353.7 436.5 261.9]
 [338.4 234.  371.7 108.9 316.8 301.5 399.6 133.2 142.2 242.1 258.3 333. ]
 [260.1 246.6 135.  416.7 138.6 308.7 377.1 207.  365.4 210.6 108.  385.2]
 [239.4 335.7 438.3 169.2 373.5 101.7 306.9 327.6 400.5 136.8 436.5 395.1]]


In [ ]:
# a. Apply np.exp() to simulate exponential growth
exp_sales = np.exp(sales_data)
print("\nExponential Growth (np.exp):\n", exp_sales)

# b. Apply np.log() to analyze sales on logarithmic scale
log_sales = np.log(sales_data)
print("\nLogarithmic Scale (np.log):\n", log_sales)

# c. Apply np.power() to simulate 1.1x monthly growth projection
growth_rate = 1.1
projected_sales = np.power(sales_data, growth_rate)
print("\nProjected Sales with 1.1x Growth (np.power):\n", projected_sales)

In [8]:
# a. Mean sales for all products over 12 months
mean_sales_all = np.mean(sales_data)
print("\nMean Sales (all products, all months):", mean_sales_all)

# b. Variance of sales for each product (row-wise)
variance_per_product = np.var(sales_data, axis=1)
print("\nVariance of Sales per Product:\n", variance_per_product)

# c. Month with lowest and highest sales for each product
min_month_index = np.argmin(sales_data, axis=1)
max_month_index = np.argmax(sales_data, axis=1)
print("\nMonth with Lowest Sales per Product:", min_month_index)
print("Month with Highest Sales per Product:", max_month_index)

# d. Standard deviation of sales for each product (row-wise)
stddev_per_product = np.std(sales_data, axis=1)
print("\nStandard Deviation of Sales per Product:\n", stddev_per_product)


Mean Sales (all products, all months): 308.45

Variance of Sales per Product:
 [10327.6875      9955.90972222 10481.24305556 12982.75
 15516.        ]

Month with Lowest Sales per Product: [ 6  1  3 10  5]
Month with Highest Sales per Product: [ 1 10  6  3  2]

Standard Deviation of Sales per Product:
 [101.62523063  99.77930508 102.37794223 113.94187114 124.56323695]
