In [1]:
import numpy as np

# 1. Data Representation
# a. Create a 10x5 array of exam scores between 40 and 100
np.random.seed(42)  # For reproducibility
scores = np.random.randint(40, 101, size=(10, 5))
print("Exam Scores (10 students x 5 subjects):\n", scores)

# 2. Element-wise Operations
# a. Total score for each student
total_scores = np.sum(scores, axis=1)
print("\nTotal score for each student:", total_scores)

# b. Percentage for each student (out of 500)
percentages = total_scores / 500 * 100
print("Percentage for each student:", percentages)

# 3. Broadcasting
# a. Add a bonus of 5 points to each score
bonus_scores = scores + 5
print("\nScores after adding 5-point bonus:\n", bonus_scores)

# 4. Universal Functions (ufunc)
# a. Simulate performance increase using np.power
enhanced_percentages = np.power(percentages, 1.1)
print("\nEnhanced percentages (raised to power 1.1):", enhanced_percentages)

# b. Logarithmic growth of the average score for each student
avg_scores = np.mean(scores, axis=1)
log_avg_scores = np.log(avg_scores)
print("Logarithmic growth of average score per student:", log_avg_scores)

# 5. Aggregation Functions
# a. Mean and median of scores for each subject (column-wise)
mean_subject = np.mean(scores, axis=0)
median_subject = np.median(scores, axis=0)
print("\nMean score per subject:", mean_subject)
print("Median score per subject:", median_subject)

# b. Best and worst performing student across all subjects
best_student_index = np.argmax(total_scores)
worst_student_index = np.argmin(total_scores)
print("\nBest performing student index:", best_student_index, "with total score:", total_scores[best_student_index])
print("Worst performing student index:", worst_student_index, "with total score:", total_scores[worst_student_index])

# c. Variance and standard deviation of scores for each student (row-wise)
variance_students = np.var(scores, axis=1)
std_students = np.std(scores, axis=1)
print("\nVariance of scores per student:", variance_students)
print("Standard deviation of scores per student:", std_students)


Exam Scores (10 students x 5 subjects):
 [[ 78  91  68  54  82]
 [ 47 100  60  78  97]
 [ 58  62  50  50  63]
 [ 92  75  79  63  42]
 [ 61  92  41  63  83]
 [ 69  77  41  99  60]
 [ 72  51  97  61 100]
 [ 83  64  88  66  98]
 [ 81  67  99  55  54]
 [ 86  90  83  94  91]]

Total score for each student: [373 382 283 351 340 346 381 399 356 444]
Percentage for each student: [74.6 76.4 56.6 70.2 68.  69.2 76.2 79.8 71.2 88.8]

Scores after adding 5-point bonus:
 [[ 83  96  73  59  87]
 [ 52 105  65  83 102]
 [ 63  67  55  55  68]
 [ 97  80  84  68  47]
 [ 66  97  46  68  88]
 [ 74  82  46 104  65]
 [ 77  56 102  66 105]
 [ 88  69  93  71 103]
 [ 86  72 104  60  59]
 [ 91  95  88  99  96]]

Enhanced percentages (raised to power 1.1): [114.81872243 117.86984012  84.74187604 107.39172623 103.69547468
 105.71015361 117.53046881 123.65257948 109.07569604 139.07666321]
Logarithmic growth of average score per student: [4.31214051 4.3359827  4.03600899 4.25134831 4.21950771 4.23700086
 4.33336146 